<?php

namespace AppBundle\Repository;

use AppBundle\Libs\Normalizer\ResultDecorator;
use AppBundle\Libs\TraitMyCase\GetMyResorces;
/**
 * AGSeguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AGSeguimientoRepository extends \AppBundle\Libs\Repository\BaseRepository {
 use GetMyResorces;
    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR) {
        
    }

    public function findAllGroupBy() {
        $qb = $this->createQueryBuilder('seguimiento');
        $qb->innerJoin('seguimiento.caso', 'caso');
        $qb->groupBy('caso');
        $qb->orderBy('seguimiento.id', 'DESC');
        $qb->andWhere($qb->expr()->eq('entity.visible', '?2'));
        $qb->setParameter(2, 1);
        return $qb->getQuery()->getResult();
    }
    

}
