<?php

namespace AppBundle\Repository;

use AppBundle\Libs\Normalizer\ResultDecorator;

/**
 * AGTipoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AGTipoClienteRepository extends \AppBundle\Libs\Repository\BaseRepository {

    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR) {
        
    }

    public function getByType($array = array(3)) {
        $qb = $this->createQueryBuilder('typeclient');
        $qb->where($qb->expr()->in('typeclient.id', $array));
        return $qb->getQuery()->getResult();
    }

}
