<?php

namespace AppBundle\Repository;

/**
 * AGTipoCobroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AGTipoCobroRepository  extends \AppBundle\Libs\Repository\BaseRepository
{
    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR) {
        
    }

}