<?php

namespace AppBundle\Repository;
use AppBundle\Libs\Normalizer\ResultDecorator;
use AppBundle\Libs\TraitMyCase\ValidateEntity;

/**
 * AGTipoCasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AGTipoCasoRepository extends \AppBundle\Libs\Repository\BaseRepository
{
    use ValidateEntity;
    public function getBaseQuery($baseEntity, $start = 0, $limit = 30, $filters = array(), $columnsAlias = array(), $decorator = ResultDecorator::DEFAULT_DECORATOR)
    {

    }
}