<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AGEmpresa extends \AppBundle\Entity\AGEmpresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'razonSocial', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'tipoIdentificacion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'numeroIdentificacion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'claveSri', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'representante', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'correo', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'ciudad', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'tipoCliente', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'casos', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'casosRectores', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'usuarioCrea', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'usuarioModifica', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'fechaCrea', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'fechaModifica', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'visible'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'razonSocial', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'tipoIdentificacion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'numeroIdentificacion', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'claveSri', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'representante', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'correo', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'ciudad', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'tipoCliente', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'casos', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'casosRectores', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'usuarioCrea', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'usuarioModifica', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'fechaCrea', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'fechaModifica', '' . "\0" . 'AppBundle\\Entity\\AGEmpresa' . "\0" . 'visible'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AGEmpresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonSocial($razonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonSocial', [$razonSocial]);

        return parent::setRazonSocial($razonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonSocial', []);

        return parent::getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoIdentificacion($tipoIdentificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoIdentificacion', [$tipoIdentificacion]);

        return parent::setTipoIdentificacion($tipoIdentificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoIdentificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoIdentificacion', []);

        return parent::getTipoIdentificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroIdentificacion($numeroIdentificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroIdentificacion', [$numeroIdentificacion]);

        return parent::setNumeroIdentificacion($numeroIdentificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroIdentificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroIdentificacion', []);

        return parent::getNumeroIdentificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaveSri($claveSri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaveSri', [$claveSri]);

        return parent::setClaveSri($claveSri);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaveSri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaveSri', []);

        return parent::getClaveSri();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepresentante($representante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepresentante', [$representante]);

        return parent::setRepresentante($representante);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentante', []);

        return parent::getRepresentante();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCrea($fechaCrea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCrea', [$fechaCrea]);

        return parent::setFechaCrea($fechaCrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCrea', []);

        return parent::getFechaCrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModifica($fechaModifica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModifica', [$fechaModifica]);

        return parent::setFechaModifica($fechaModifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModifica', []);

        return parent::getFechaModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(\AppBundle\Entity\AGCiudad $ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoCliente(\AppBundle\Entity\AGTipoCliente $tipoCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoCliente', [$tipoCliente]);

        return parent::setTipoCliente($tipoCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoCliente', []);

        return parent::getTipoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function addCaso(\AppBundle\Entity\AGCaso $caso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaso', [$caso]);

        return parent::addCaso($caso);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaso(\AppBundle\Entity\AGCaso $caso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaso', [$caso]);

        return parent::removeCaso($caso);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasos', []);

        return parent::getCasos();
    }

    /**
     * {@inheritDoc}
     */
    public function addCasosRectore(\AppBundle\Entity\AGCaso $casosRectore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCasosRectore', [$casosRectore]);

        return parent::addCasosRectore($casosRectore);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCasosRectore(\AppBundle\Entity\AGCaso $casosRectore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCasosRectore', [$casosRectore]);

        return parent::removeCasosRectore($casosRectore);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasosRectores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasosRectores', []);

        return parent::getCasosRectores();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuario(\AppBundle\Entity\AGUsuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuario', [$usuario]);

        return parent::addUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuario(\AppBundle\Entity\AGUsuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuario', [$usuario]);

        return parent::removeUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioCrea(\AppBundle\Entity\AGUsuario $usuarioCrea = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioCrea', [$usuarioCrea]);

        return parent::setUsuarioCrea($usuarioCrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioCrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioCrea', []);

        return parent::getUsuarioCrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioModifica(\AppBundle\Entity\AGUsuario $usuarioModifica = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioModifica', [$usuarioModifica]);

        return parent::setUsuarioModifica($usuarioModifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioModifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioModifica', []);

        return parent::getUsuarioModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function getCasosReales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasosReales', []);

        return parent::getCasosReales();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalDeuda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalDeuda', []);

        return parent::getTotalDeuda();
    }

}
