<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AGCaso extends \AppBundle\Entity\AGCaso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'honorarios', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'resolucion', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'ciudad', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'tipocaso', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'empresaRectora', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'responsable', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'intermediario', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'detalles', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'seguimiento', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'pagoRealizado', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'usuarioCrea', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'usuarioModifica', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'fechaCrea', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'fechaModifica', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'visible'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'honorarios', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'resolucion', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'ciudad', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'tipocaso', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'empresaRectora', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'responsable', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'intermediario', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'detalles', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'seguimiento', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'pagoRealizado', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'usuarioCrea', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'usuarioModifica', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'fechaCrea', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'fechaModifica', '' . "\0" . 'AppBundle\\Entity\\AGCaso' . "\0" . 'visible'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AGCaso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setHonorarios($honorarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHonorarios', [$honorarios]);

        return parent::setHonorarios($honorarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getHonorarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHonorarios', []);

        return parent::getHonorarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setResolucion($resolucion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResolucion', [$resolucion]);

        return parent::setResolucion($resolucion);
    }

    /**
     * {@inheritDoc}
     */
    public function getResolucion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResolucion', []);

        return parent::getResolucion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(\AppBundle\Entity\AGCiudad $ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\AppBundle\Entity\AGEstado $estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipocaso(\AppBundle\Entity\AGTipoCaso $tipocaso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipocaso', [$tipocaso]);

        return parent::setTipocaso($tipocaso);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipocaso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipocaso', []);

        return parent::getTipocaso();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\AppBundle\Entity\AGEmpresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', [$empresa]);

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable(\AppBundle\Entity\AGUsuario $responsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntermediario(\AppBundle\Entity\AGUsuario $intermediario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntermediario', [$intermediario]);

        return parent::setIntermediario($intermediario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntermediario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntermediario', []);

        return parent::getIntermediario();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalle(\AppBundle\Entity\AGDetalle $detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalle', [$detalle]);

        return parent::addDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetalle(\AppBundle\Entity\AGDetalle $detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetalle', [$detalle]);

        return parent::removeDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalles', []);

        return parent::getDetalles();
    }

    /**
     * {@inheritDoc}
     */
    public function addSeguimiento(\AppBundle\Entity\AGSeguimiento $seguimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSeguimiento', [$seguimiento]);

        return parent::addSeguimiento($seguimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSeguimiento(\AppBundle\Entity\AGSeguimiento $seguimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSeguimiento', [$seguimiento]);

        return parent::removeSeguimiento($seguimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeguimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeguimiento', []);

        return parent::getSeguimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function addPagoRealizado(\AppBundle\Entity\AGPagoRealizado $pagoRealizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPagoRealizado', [$pagoRealizado]);

        return parent::addPagoRealizado($pagoRealizado);
    }

    /**
     * {@inheritDoc}
     */
    public function removePagoRealizado(\AppBundle\Entity\AGPagoRealizado $pagoRealizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePagoRealizado', [$pagoRealizado]);

        return parent::removePagoRealizado($pagoRealizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoRealizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoRealizado', []);

        return parent::getPagoRealizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCrea($fechaCrea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCrea', [$fechaCrea]);

        return parent::setFechaCrea($fechaCrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCrea', []);

        return parent::getFechaCrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModifica($fechaModifica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModifica', [$fechaModifica]);

        return parent::setFechaModifica($fechaModifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModifica', []);

        return parent::getFechaModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioCrea(\AppBundle\Entity\AGUsuario $usuarioCrea = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioCrea', [$usuarioCrea]);

        return parent::setUsuarioCrea($usuarioCrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioCrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioCrea', []);

        return parent::getUsuarioCrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioModifica(\AppBundle\Entity\AGUsuario $usuarioModifica = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioModifica', [$usuarioModifica]);

        return parent::setUsuarioModifica($usuarioModifica);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioModifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioModifica', []);

        return parent::getUsuarioModifica();
    }

    /**
     * {@inheritDoc}
     */
    public function getDineroPagado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDineroPagado', []);

        return parent::getDineroPagado();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagosReales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagosReales', []);

        return parent::getPagosReales();
    }

    /**
     * {@inheritDoc}
     */
    public function getProximoPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProximoPago', []);

        return parent::getProximoPago();
    }

    /**
     * {@inheritDoc}
     */
    public function tienePagosPendientes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tienePagosPendientes', []);

        return parent::tienePagosPendientes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaRectora(\AppBundle\Entity\AGEmpresa $empresaRectora = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaRectora', [$empresaRectora]);

        return parent::setEmpresaRectora($empresaRectora);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaRectora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaRectora', []);

        return parent::getEmpresaRectora();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

}
